#!/bin/bash

function _install_webroot () {
  mkdir --parents "$1"/images
  mkdir --parents "$1"/php
  mkdir --parents "$1"/scripts
  mkdir --parents "$1"/style
  mkdir --parents "$1"/utility
  mkdir --parents "$1"/utility/control
  install -p -t "$1" *.html *.php favicon.ico
  rm "$1"/phpinfo.php
  install -p -t "$1"/php php/*.*
  install -p -t "$1"/scripts scripts/*.*
  install -p -t "$1"/style style/*.*
  install -p -t "$1"/images images/*.*
  install -p -t "$1"/php templates/webconfig.php
  rm "$1"/php/config.php
  mv "$1"/php/webconfig.php ~/board18-$versionNo/webroot/php/config.php
  rm "$1"/php/configMail.php
  install -p -t "$1"/php templates/configMail.php
}

function _install_utility () {
  install -p -t "$1" utility/*
  install -p -t "$1" templates/utilconfig.php
  rm "$1"/config.php
  mv "$1"/utilconfig.php ~/board18-$versionNo/utility/config.php
}

source $(dirname $0)/config.sh
# Create a new distribution of BOARD18
cd $BD18Root
rm -f ~/board18-$versionNo.zip
rm -f -r ~/board18-$versionNo
mkdir ~/board18-$versionNo

mkdir ~/board18-$versionNo/webroot
_install_webroot ~/board18-$versionNo/webroot

install -p -t ~/board18-$versionNo Documentation/README.txt
install -p -t ~/board18-$versionNo Documentation/LICENSE.txt
install -p -t ~/board18-$versionNo Documentation/INSTALL.txt
install -p -t ~/board18-$versionNo Documentation/DOCKER.txt
install -p -t ~/board18-$versionNo Documentation/ReleaseNotes.txt

mkdir ~/board18-$versionNo/utility
_install_utility ~/board18-$versionNo/utility

# Create a Docker context
mkdir ~/board18-$versionNo/docker
install -p -t ~/board18-$versionNo/docker docker/*
install -p -t ~/board18-$versionNo/docker docker/.env
mkdir ~/board18-$versionNo/docker/webroot
_install_webroot ~/board18-$versionNo/webroot
mkdir ~/board18-$versionNo/docker/utility
_install_utility ~/board18-$versionNo/docker/utility

cd ~
zip -r ~/board18-$versionNo.zip board18-$versionNo
rm -f -r ~/board18-$versionNo
