#!/bin/bash 
#
# This script will create a new game box row in the box
# table of the board18 database for each JSON file in 
# the given diectory.
# The positional input parameter is as follows:
#   directory  -  qualified directory name
# 
# Each JSON file should contain the complete json
# object for a game box as a text file.
# 
# The script will display each newly created row.
#
if [ $# -ne 1 ]
then 
   echo "Usage: loadAllBoxes directory"
   exit
fi
shopt -s nullglob
for file in $1/*
do
  ./loadGameBox.php $file 
done
shopt -u nullglob #revert nullglob back to it's default state
